version: '3.8'

services:
  gin-rest-api:
    build: ./
    command: ./wait-for-postgres.sh db ./gin-rest-api
    ports:
      - 8080
    depends_on:
      - db
    environment:
      POSTGRES_PASSWORD: 260616


  db:
      restart: always
      image: postgres:latest
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: 260616
        POSTGRES_DB: go_test
        PGDATA: /var/lib/postgresql/data/pgdata
      volumes:
        - ./init.sql:/docker-entrypoint-initdb.d/football_script.sql 
      ports:
        - 5436:5432
