postgres:
  host: "localhost"
  port: 5432
  user: "postgres"
  password: "260616"
  dbName: "go_test"
  sslMode: "disable" 

server:
  internalPort: 8080

jwt:
  secret: "jwt-token-secret"
  refreshSecret: "mySecretKey"
  accessTokenExpireDuration: 1440m
  refreshTokenExpireDuration: 60m